[workspace]
members = ["crates/embedding", "crates/parsing", "crates/transcription"]
edition = "2024"
resolver = "3"

[workspace.dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
