[package]
name = "ragzilla-transcription"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
reqwest = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
dotenvy = { workspace = true }
