[package]
name = "ragzilla-parsing"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
tokio = { version = "1.44.1", features = ["full"] }
dotenvy = "0.15.7"
